services:
  app:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://manga_user:manga_password@db:5432/manga_db?sslmode=disable
      - SERVER_ADDRESS=0.0.0.0:8888
    networks:
      - manga-network

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=manga_user
      - POSTGRES_PASSWORD=manga_password
      - POSTGRES_DB=manga_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - manga-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  manga-network:
    driver: bridge